Traceback (most recent call last):
  File "c:\Users\volat\Desktop\Python\Training\errorExample.py", line 4, in <module>
    raise Exception("This is the error message.")
Exception: This is the error message.
